"""Add notification_type, review_status, review_comment, and activity_title to Notification model

Revision ID: 10668df379f4
Revises: dcfbb0d16cd7
Create Date: 2025-06-08 22:58:24.019529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10668df379f4'
down_revision = 'dcfbb0d16cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('activity_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('review_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('review_comment', sa.Text(), nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', mysql.TEXT(), nullable=False))
        batch_op.drop_column('review_comment')
        batch_op.drop_column('review_status')
        batch_op.drop_column('activity_title')
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
