"""Add ondelete CASCADE to Notification.activity_id

Revision ID: dcfbb0d16cd7
Revises: a549e72489bd
Create Date: 2025-06-07 19:11:18.185608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfbb0d16cd7'
down_revision = 'a549e72489bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notification_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notification_ibfk_1'), 'activity', ['activity_id'], ['id'])

    # ### end Alembic commands ###
